### ISSUE TITLE
Implementation of 3D gaze estimation

### ISSUE THREAD

**Issue by avisekiit** [wayaai/SimGAN#14]
Hi,
Thanks for this awesome repo. However, did you actually continue on to do the 3D gaze estimation after this GAN based domain adaptation?

**Comment by mjdietzx** [comment]
Hey, I did not do any 3D gaze estimation. I used SimGAN in my projects internally on completely different task than gaze estimation. I just released code w/ gaze estimation data set so people could get started quickly and b/c original paper used that dataset
