### ISSUE TITLE
unexpected 'dim_ordering'

### ISSUE THREAD

**Issue by genemiller** [wayaai/SimGAN#4]
Could you provide suggestions for diagnosing this error: `TypeError:  __init__() got an unexpected keyword argument 'dim_ordering'`?

This file [SimGAN-dim_ordering.txt](https://github.com/wayaai/SimGAN/files/982020/SimGAN-dim_ordering.txt) lists software versions and the run log.

Thanks
Gene Miller
gene.miller@nyu.edu

**Comment by genemiller** [comment]
The the call to `image.ImageDataGenerator` in the Kaggle notebook uses `data_format='channels_last'` instead of `dim_ordering='tf'`
I will try this fix. Meanwhile, I'm closing this issue for now.

**Comment by mjdietzx** [comment]
You most likely are using an outdated version of keras. Update to keras v2 (pip install -U keras). If not possible for you to update revert to a commit before I updated code for keras v2

**Comment by zhengziqiang** [comment]
I met this error while using the Keras v2.0.

**Comment by zhengziqiang** [comment]
It works when I commented remove the dim_ordering='tf'
    datagen = image.ImageDataGenerator(
        preprocessing_function=applications.xception.preprocess_input)
